import './globals.css'
import type { Metadata } from 'next'
import { Play } from 'next/font/google'

import Header from './component/header';
import Footer from './component/footer';

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const play = Play({
  subsets: ['latin'],
  weight:["700"],
  display: 'swap',
  variable: '--font-play',
}) // google fonts 

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${play.variable}`}>
      <body>
          <Header/>
          {children}
          <Footer/>
      </body>
    </html>
  )
}
